Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# from aleatory.processes import BESQProcess
process = BESQProcess(dim= 3.5, initial=1.0)
Y_1 = process.get_marginal(t=1)
y = np.linspace(0, Y_1.ppf(0.999), 200)
plt.plot(y, Y_1.pdf(y), '-', lw=1.5, alpha=0.75, label=f'$t$={1:.2f}')
plt.title(f'$Y_1$ pdf from a ' + process.name + ' process')
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [4][0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m [38;5;66;03m# from aleatory.processes import BESQProcess[39;00m
[0;32m----> 2[0m process [38;5;241m=[39m [43mBESQProcess[49m(dim[38;5;241m=[39m [38;5;241m3.5[39m, initial[38;5;241m=[39m[38;5;241m1.0[39m)
[1;32m      3[0m Y_1 [38;5;241m=[39m process[38;5;241m.[39mget_marginal(t[38;5;241m=[39m[38;5;241m1[39m)
[1;32m      4[0m y [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m0[39m, Y_1[38;5;241m.[39mppf([38;5;241m0.999[39m), [38;5;241m200[39m)

[0;31mNameError[0m: name 'BESQProcess' is not defined
NameError: name 'BESQProcess' is not defined

